fix certs_gen

diff --git a/shell/certs_gen b/shell/certs_gen
--- a/shell/certs_gen
+++ b/shell/certs_gen
@@ -352,10 +352,8 @@ certs_dealing() {
         if test -e $certs_cert -a -e $certs_private_key ; then
             dn=`ipsec pki --print --in $certs_cert | grep "subject" | sed "s/.*:\ *\(.*\)\"$/\1/g"`
             certs_dir=`echo $dn | sed "s/[,\ =]\{1,\}/_/g"`
-            ca_dn=`ipsec pki --print --in $ca_cert | grep "issuer" | sed "s/.*:\ *\(.*\)\"$/\1/g"`
-            ca_dir=`echo $ca_dn | sed "s/[,\ =]\{1,\}/_/g"`
-            
             certs_path=$certs_gen_path/ca/$ca_dir/$certs_dir
+            
             if test ! -e $certs_path ; then
                 mkdir -p $certs_path
                 cp -f $certs_private_key $certs_path
@@ -370,11 +368,13 @@ certs_dealing() {
         certs_path=""
         
         test -z "$dn" && echo "Please input certificate dn!" && exit 1
-        if test -z "$ipsec_certs_save_file" ; then
+        if test ! -e "$ipsec_certs_save_file" ; then
+            certs_dir=`echo $dn | sed "s/[,\ =]\{1,\}/_/g"`
             certs_already_exist=0
         else
             certs_result=`grep "$dn" $ipsec_certs_save_file`
             if test -z "$certs_result" ; then
+                certs_dir=`echo $dn | sed "s/[,\ =]\{1,\}/_/g"`
                 certs_already_exist=0
             else
                 certs_path=`echo $certs_result | awk -F':' '{ print $3 }'`
@@ -410,8 +410,24 @@ ca_dealing() {
     else
         ca_cert=""
         ca_private_key=""
-       
+        ca_already_exist=0
+
+        if test $certs_already_exist -eq 2 ; then
+            certs_ca_dn=`ipsec pki --print --in $ca_cert | grep "issuer" | sed "s/.*:\ *\(.*\)\"$/\1/g"`
+            certs_ca_dir=`echo $ca_dn | sed "s/[,\ =]\{1,\}/_/g"`
+            certs_ca_path=$certs_gen_path/ca/$ca_dir
+            if test -e $certs_ca_path ; then
+                ca_cert=`find $certs_ca_path -maxdepth 1 -type f | grep ".*cert.pem"`
+                ca_private_key=`find $certs_ca_path  -maxdepth 1 -type f | grep ".*private_key.pem"`
+                ca_path=`dirname $certs_ca_cert`
+                ca_dir=`basename $certs_ca_path`
+            else
+                certs_ca_dn=""
+            fi
+        fi
+        test -z "$ca_dn" -a -n "$certs_ca_dn" && ca_dn=$certs_ca_dn
         test -z "$ca_dn" && echo "No ca cert and private key!" && exit 1
+
         if test $certs_already_exist -eq 1; then
             ca_dn=`grep "$dn" $ipsec_certs_save_file | awk -F':' '{ print $1 }' | sed 1p -n`
             test -z "$ca_dn" && echo "Cannot get ca dn!" && exit 1
@@ -429,18 +445,27 @@ ca_dealing() {
             ca_cert=$ca_path/$ca_cert
             ca_dir=`basename $ca_path`
             ca_already_exist=1
-        else if test $certs_already_exist -eq 2 ; then
+        fi
+
+        if test $certs_already_exist -eq 0 ; then
             ca_dir=`echo $ca_dn | sed "s/[,\ =]\{1,\}/_/g"`
             ca_path=$certs_gen_path/ca/$ca_dir
-            test ! -e $ca_path && echo "No ca \"$ca_dn\"!" && exit 1
-            ca_already_exist=1
-        else
-            ca_already_exist=0
+
+            if test -e $ca_path ; then
+                ca_cert=`find $ca_path -maxdepth 1 -type f | grep ".*cert.pem"`
+                ca_private_key=`find $ca_path -maxdepth 1 -type f | grep ".*private_key.pem"`
+                test -z "$ca_cert" && echo "Could not find ca certificate!" && exit 1
+                test -z "$ca_private_key" && echo "Could not find ca private key!" && exit 1
+                ca_path=`dirname $ca_cert`
+                ca_dir=`basename $ca_path`
+            else
+                echo "Generate certificate \"$dn\" need CA \"$ca_dn\"!" && exit 1
+            fi
         fi
     fi
 
-    test ! -e "$ca_private_key" && echo "Could not find \"$ca_private_key\"!" && exit 1
-    test ! -e "$ca_cert" && echo "Could not find \"$ca_cert\"!" && exit 1
+    test ! -e "$ca_private_key" && echo "CA private key \"$ca_private_key\" does not exist!" && exit 1
+    test ! -e "$ca_cert" && echo "CA certificate \"$ca_cert\" does not exist!" && exit 1
 }
 
 certs_gen_path=~/.ipsec_certs
@@ -508,43 +533,29 @@ fi
 ##
 test -z "$dn" && test -z "$ca_dn" && dn=$default_certs_dn
 test -z "$dn" && test -n "$ca_dn" && dn=$ca_dn
-test -z "$name" && name=`echo $dn | sed "s/.*CN=\(.*\)[\$@#\'\"+=,:|\\\!~?]\{1,\}.*$/\1/g" | tr '[A-Z]' '[a-z]' | sed "s/\ /_/g"`
-
-##
-# check certs whether already generated
-##
-if test $package_certs -eq 1; then
-    if test -n "$certs_cert" -a -n "$certs_private_key"; then
-        package_certs_already_exist=1
-    else
-        certs_cert=""
-        certs_private_key=""
-        if test ! -e $ipsec_certs_save_file ; then
-            package_certs_already_exist=0
-        else        
-            certs_path=`grep "$dn" $ipsec_certs_save_file | awk -F':' '{ print $3 }' | sed 1p -n`
-            if test -z "$certs_path" ; then
-                package_certs_already_exist=0
-            else
-                test ! -e "$certs_path" && echo "Certificates path \"$certs_path\" does not exist!" && exit 1
-                package_certs_already_exist=1
-            fi
-        fi
-    fi
+if test -z "$name"; then
+    name=`echo "$dn" | sed "s/.*CN\ *=\ *\(.*\)$/\1/g"`
+    test -z "$name" && echo "Certificate name cannot be null!" && exit 1
+    name=${name//[\$@#\'\"+=,:|\\\!~?]*/}
+    test -z "$name" && echo "Certificate name cannot be null!" && exit 1
+    name=`echo $name | tr 'A-Z' 'a-z' | sed "s/\ /_/g"`
+    test -z "$name" && echo "Certificate name cannot be null!" && exit 1
 fi
 
 ##
 # ca dealing
 ##
-ca_dealing
+certs_dealing
+ca_dealing 
 
 ##
 # check whether package
 ##
 test -z "$dn" -a -z "$certs_cert" -a -z "$certs_private_key" && echo "Input parameters error!" && exit 1
-certs_dir=`echo $dn | sed "s/[,\ =]\{1,\}/_/g"`
-certs_path=$ca_path/$certs_dir
-if test $package_certs_already_exist -eq 1 ; then
+if test $certs_already_exist -ne 0 ; then
+    certs_cert=$certs_gen_path/ca/$ca_dir/$certs_dir
+fi
+if test $package_certs -eq 1 ; then
     if test -z "$certs_cert" ; then
         certs_cert=`grep "$dn" $ipsec_certs_save_file | awk -F':' '{ print $5 }' | sed 1p -n`
         test -z "$certs_cert" && echo "Cannot get certificate name!" && exit 1
@@ -572,12 +583,12 @@ if test $package_certs_already_exist -eq 1 ; then
     exit 1
 fi
 
-if test -n "$certs_cert" -a -n "$certs_private_key"; then
-    test -e $certs_cert -a -e $certs_private_key && echo "Certificate already exist!" && exit 1
-fi
 ##
 # check whether already exist
 ##
+test $package_certs -eq 1 && echo "Package certificates \"$dn\" failed!" && exist 1
+test $certs_already_exist -gt 0 && echo "Certificate with subject \"$dn\" already created!" && exit 1
+certs_path=$certs_gen_path/ca/$ca_dir/$certs_dir
 test -d $certs_path && echo "Certificate with subject \"$dn\" already created!" && exit 1
 mkdir -p $certs_path
 
